version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/ml/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
