services:
  db:
    image: timescale/timescaledb:2.14.2-pg16
    container_name: mt5_db
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://trader:trader123@db:5432/mt5_trading"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "trader"
      DB_PASS: "trader123"
      POSTGRES_USER: ${POSTGRES_USER:-trader}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-trader123}
      POSTGRES_DB: ${POSTGRES_DB:-mt5_trading}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-trader} -d ${POSTGRES_DB:-mt5_trading} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: mt5-api
    container_name: mt5_api
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql+psycopg://${POSTGRES_USER:-trader}:${POSTGRES_PASSWORD:-trader123}@db:5432/${POSTGRES_DB:-mt5_trading}}"
      PORT: ${API_PORT_INTERNAL:-8001}
      UVICORN_WORKERS: ${UVICORN_WORKERS:-1}
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "trader"
      DB_PASS: "trader123"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT:-8001}:8001"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8001
      --access-log
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request, sys;\n\ntry:\n    r=urllib.request.urlopen('http://localhost:8001/health', timeout=2)\n    if r.read().strip():\n        sys.exit(0)\n    else:\n        sys.exit(1)\nexcept Exception:\n    sys.exit(1)\n\" || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: mt5_pgadmin
    restart: unless-stopped
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT:-5050}:80"

volumes:
  db_data:
