services:
  db:
    image: timescale/timescaledb:2.16.1-pg16
    container_name: mt5_db
    env_file: .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-trader}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-trader123}"
      POSTGRES_DB: "${POSTGRES_DB:-mt5_trading}"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/timescaledb:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-trader} -d ${POSTGRES_DB:-mt5_trading}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  mt5_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mt5_api
    env_file: .env
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql+psycopg://trader:trader123@db:5432/mt5_trading}"
      API_PORT: "8001"
      PYTHONPATH: "/app"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./api:/app/api:rw       # agora existe /app/api/main.py
      - ./logs:/app/logs
      - ./data/raw:/app/data_raw
    command: uvicorn api.main:app --host 0.0.0.0 --port 8001
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: mt5_pgadmin
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-admin@example.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin123}"
    depends_on:
      - db
    ports:
      - "5050:80"
    restart: unless-stopped

networks:
  default:
    name: mt5-trading-db_default
