services:
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_DB=mt5_trading
      - POSTGRES_USER=trader
      - POSTGRES_PASSWORD=trader123
    ports:
      - "6005:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U trader -d mt5_trading"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - timescaledb:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    environment:
      - DATABASE_URL=postgresql://trader:trader123@db:5432/mt5_trading
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8005:8000"   # trocado de 8001 -> 8005
    volumes:
      - models_mt5:/models

  ml-trainer:
    build:
      context: .
      dockerfile: ml/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks: [default]
    volumes:
      - models_mt5:/models

  ml-scheduler:
    build:
      context: .
      dockerfile: ml/Dockerfile
    command: python -u ml/scheduler.py
    depends_on:
      db:
        condition: service_healthy
    networks: [default]
    volumes:
      - models_mt5:/models
    restart: unless-stopped

volumes:
  timescaledb:
  models_mt5:
