services:
  db:
    image: timescale/timescaledb:2.14.2-pg16
    environment:
      # The repository's .env defines DB_NAME/DB_USER/DB_PASS — map them to the
      # Postgres entrypoint variables expected by the image.
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    # Map Postgres container port 5432 to host. Default to 6005 to avoid
    # colliding with a host Postgres on 5432.
    ports: [ "${DB_PORT:-6005}:5432" ]
    volumes: [ "db_data:/var/lib/postgresql/data", "./db/init:/docker-entrypoint-initdb.d" ]
    restart: unless-stopped

  api:
    build: ./api
    environment:
      # Prefer an explicit DATABASE_URL if provided, otherwise construct one
      # from the mapped DB_* variables. The host should be the service name `db`.
      DATABASE_URL: ${DATABASE_URL:-postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}}
      API_HOST: 0.0.0.0
      API_PORT: 8001
      ALLOW_ORIGINS: "*"
    depends_on:
      db: { condition: service_healthy }
    ports: ["${API_PORT:-8001}:8001"]
    restart: unless-stopped

volumes:
  db_data:
