services:
  api:
    ports:
      - "${API_PORT:-8001}:8001"
    volumes:
      - models_mt5:/models
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  ml-scheduler:
    build:
      context: .
      dockerfile: ml/Dockerfile
    command: python -u ml/scheduler.py
    depends_on: [db]
    env_file: [.env]
    volumes:
      - models_mt5:/models
    networks: [mt5_net]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  ml-trainer:
    build:
      context: .
      dockerfile: ml/Dockerfile
    command: python -u ml/train_worker.py
    depends_on: [db]
    env_file: [.env]
    volumes:
      - models_mt5:/models
    networks: [mt5_net]
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

networks:
  mt5_net:
    name: mt5_net

volumes:
  models_mt5:
    name: models_mt5
    external: true
