openapi: 3.0.3
info:
  title: MT5 Trading API
  version: "1.0.0"
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /predict:
    get:
      summary: Predict latest probability for a symbol
      parameters:
        - in: query
          name: symbol
          required: true
          schema: { type: string }
        - in: query
          name: limit
          required: false
          schema: { type: integer, default: 30 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  symbol: { type: string }
                  n: { type: integer }
                  prob_up_latest: { type: number, format: float }
                  ts_latest: { type: string, format: date-time }
        '404': { description: Not found }
        '401': { description: Unauthorized }
        '429': { description: Rate limited }
