# Default values for mt5-trading
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global settings
global:
  namespace: mt5-trading
  storageClass: manual

## PostgreSQL / TimescaleDB
postgres:
  enabled: true
  image:
    repository: timescale/timescaledb
    tag: 2.14.2-pg16
    pullPolicy: IfNotPresent
  
  auth:
    username: trader
    password: change-me-in-production
    database: mt5_trading
  
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 2000m
  
  persistence:
    enabled: true
    size: 20Gi
    storageClass: manual
  
  service:
    type: ClusterIP
    port: 5432

## API
api:
  enabled: true
  replicaCount: 2
  
  image:
    repository: mt5-trading-api
    tag: latest
    pullPolicy: IfNotPresent
  
  apiKey: mt5_trading_secure_key_2025_prod
  
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 1000m
  
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8000
  
  ingress:
    enabled: true
    className: nginx
    host: api.mt5-trading.local
    tls:
      enabled: true
      secretName: mt5-trading-tls
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

## Machine Learning
ml:
  enabled: true
  
  trainer:
    image:
      repository: mt5-trading-ml
      tag: latest
      pullPolicy: IfNotPresent
    
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 2000m
  
  scheduler:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 8Gi
        cpu: 4000m
  
  persistence:
    enabled: true
    size: 5Gi
    storageClass: manual

## Prometheus
prometheus:
  enabled: true
  
  image:
    repository: prom/prometheus
    tag: v2.52.0
    pullPolicy: IfNotPresent
  
  retention: 15d
  scrapeInterval: 5s
  
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 1000m
  
  persistence:
    enabled: true
    size: 10Gi
    storageClass: manual
  
  service:
    type: ClusterIP
    port: 9090
  
  ingress:
    enabled: true
    className: nginx
    host: prometheus.mt5-trading.local
    tls:
      enabled: true
      secretName: mt5-trading-tls

## Grafana
grafana:
  enabled: true
  
  image:
    repository: grafana/grafana
    tag: 11.0.0
    pullPolicy: IfNotPresent
  
  auth:
    adminUser: admin
    adminPassword: admin
  
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  
  persistence:
    enabled: true
    size: 2Gi
    storageClass: manual
  
  service:
    type: LoadBalancer
    port: 3000
  
  ingress:
    enabled: true
    className: nginx
    host: grafana.mt5-trading.local
    tls:
      enabled: true
      secretName: mt5-trading-tls

## ConfigMaps and Secrets
config:
  logLevel: INFO
  workers: 4
  timescaledb:
    telemetry: "off"

## ServiceAccount
serviceAccount:
  create: true
  name: mt5-trading-sa

## RBAC
rbac:
  create: true
