apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mt5-trading

bases:
  - ../../base

commonLabels:
  environment: production

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mt5-api
      spec:
        replicas: 3
    target:
      kind: Deployment
      name: mt5-api

  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: mt5-api-hpa
      spec:
        minReplicas: 3
        maxReplicas: 10
    target:
      kind: HorizontalPodAutoscaler
      name: mt5-api-hpa

configMapGenerator:
  - name: mt5-trading-config
    behavior: merge
    literals:
      - LOG_LEVEL=WARNING
      - WORKERS=4

# Note: In production, use external secrets management (Vault, AWS Secrets Manager, etc.)
secretGenerator:
  - name: mt5-trading-secrets
    behavior: merge
    literals:
      - POSTGRES_PASSWORD=CHANGE_ME_PRODUCTION_PASSWORD
      - API_KEY=CHANGE_ME_PRODUCTION_API_KEY
      - GF_SECURITY_ADMIN_PASSWORD=CHANGE_ME_PRODUCTION_ADMIN_PASSWORD
