apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mt5-trading
  labels:
    app: grafana
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        component: monitoring
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - name: grafana
        image: grafana/grafana:11.0.0
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: mt5-trading-config
        - secretRef:
            name: mt5-trading-secrets
        env:
        - name: GF_PATHS_PROVISIONING
          value: /etc/grafana/provisioning
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        - name: provisioning-datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
        - name: provisioning-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
          readOnly: true
        - name: dashboard-json
          mountPath: /var/lib/grafana/dashboards
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: provisioning-datasources
        configMap:
          name: grafana-datasources
      - name: provisioning-dashboards
        configMap:
          name: grafana-dashboards-provisioning
      - name: dashboard-json
        configMap:
          name: grafana-dashboard-json

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: mt5-trading
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: grafana

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mt5-trading
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true

      - name: PostgreSQL
        type: postgres
        access: proxy
        url: postgres-service:5432
        database: mt5_trading
        user: trader
        secureJsonData:
          password: change-me-in-production
        jsonData:
          sslmode: disable
          postgresVersion: 1600
          timescaledb: true
        editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provisioning
  namespace: mt5-trading
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'MT5 Trading'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
