apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mt5-trading-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mt5-api
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: mt5-api

  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: mt5-api-hpa
      spec:
        minReplicas: 1
        maxReplicas: 3
    target:
      kind: HorizontalPodAutoscaler
      name: mt5-api-hpa

configMapGenerator:
  - name: mt5-trading-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - WORKERS=2

secretGenerator:
  - name: mt5-trading-secrets
    behavior: merge
    literals:
      - POSTGRES_PASSWORD=dev_password_123
      - API_KEY=dev_api_key_12345
      - GF_SECURITY_ADMIN_PASSWORD=dev_admin
