name: Health Check Monitoring

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Manual trigger

jobs:
  health-check:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run health check
        run: |
          cd /home/felipe/mt5-trading-db
          ./scripts/health-check.sh
      
      - name: Check for critical alerts
        run: |
          cd /home/felipe/mt5-trading-db
          ALERT_COUNT=$(sqlite3 logs/health-checks/health_checks.db "SELECT COUNT(*) FROM alerts WHERE resolved=0;")
          echo "Active alerts: $ALERT_COUNT"
          
          if [ "$ALERT_COUNT" -gt 0 ]; then
            echo "::warning::There are $ALERT_COUNT active alerts!"
            sqlite3 logs/health-checks/health_checks.db "SELECT component_name, alert_type, message FROM alerts WHERE resolved=0;" | while IFS='|' read comp type msg; do
              echo "::warning::Alert: $comp - $type - $msg"
            done
          fi
  
  daily-report:
    runs-on: self-hosted
    # Run at 5:00 AM UTC-3 (8:00 AM UTC) daily
    if: github.event.schedule == '0 8 * * *'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate daily report
        run: |
          cd /home/felipe/mt5-trading-db
          ./scripts/health-check.sh --report
      
      - name: Archive report
        run: |
          cd /home/felipe/mt5-trading-db/logs/health-checks
          TODAY=$(date +%Y-%m-%d)
          if [ -f "daily_report_$TODAY.txt" ]; then
            echo "Daily report generated successfully"
            cat "daily_report_$TODAY.txt"
          fi
