name: Pre-commit Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pre-commit e dependências
        run: |
          pip install pre-commit
          pre-commit install

      - name: Rodar pre-commit em todos os arquivos
        run: pre-commit run --all-files
